##################################################################################
# Cloudify Mircosoft Azure types and plugins definitions.
##################################################################################

plugins:
  microsoft:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-azure-plugin/archive/1.2.zip

node_types:
  cloudify.azure.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      TDB...
	  TDB...
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: microsoft.azure.server.create_vm
        start:
          implementation: microsoft.azure.server.start_vm
        stop:
          implementation: microsoft.azure.server.stop_vm
        delete:
          implementation: microsoft.azure.delete.delete_virtual_machine
      cloudify.interfaces.validation:
        creation:
          implementation: microsoft.azure.server.vm_creation_validation

  cloudify.azure.nodes.ElasticIP:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      location:
        description: >
          The location where the resource group would be created.
        type: String
        default: ''
      resource_group_name:
        description: >
          The name of resource group where the VM has to be created.
        type: String
        default: ''
        
        TBD
