##################################################################################
# Cloudify Azure built in types and plugins definitions.
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-azure-plugin/archive/master.zip

node_types:
  cloudify.azure.nodes.ResourceGroup:
    derived_from: cloudify.nodes.Root
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create resource group
        type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
        type: string
        default: 'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine required to create resource group
        type: string
        default: 'my_vm'
      
    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.resourcegroup.create_resource_group
        delete: azure.resourcegroup.delete_resource_group
      cloudify.interfaces.validation:
        creation: azure.resourcegroup.resource_group_creation_validation
        
  cloudify.azure.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      location:
        description: >
          Indicates the location where VM will be provisioned
        type: string
        default: 'West US'
      subscription_id:
        description: >
          Indicates the subscription id of user account
        type: string
        default: ''
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default: 'my_vm'
      vm_size:
        description: >
          Indicates the size of VM
        type: string
        default: 'Standard A0'
      vm_os_type:
        description: >
          Flavour of virtual machine
        type: string
        default: 'UbuntuServer'
      key_data:
        description: >
           Indicates the ssh public-key data of the user
        type: string
        default: ''
    
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.server.create_vm
        start:
          implementation: azure.server.start_vm
        stop:
          implementation: azure.server.stop_vm
        delete:
          implementation: azure.server.delete_virtual_machine
      cloudify.interfaces.validation:
        creation:
          implementation: azure.server.vm_creation_validation

  cloudify.azure.nodes.PublicIP:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create public ip address. 
        type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
        type: string
        default: 'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default: 'my_vm'     

    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.publicip.create_public_ip
        delete: azure.publicip.delete_public_ip
      cloudify.interfaces.validation:
        creation: azure.publicip.public_ip_creation_validation

  cloudify.azure.nodes.StorageAccount:
    derived_from: cloudify.nodes.Container
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create public ip address. 
        type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
        type: string
        default: 'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default: 'my_vm'
      
    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.storageaccount.create_storage_account
        delete: azure.storageaccount.delete_storage_account
      cloudify.interfaces.validation:
        creation: azure.storageaccount.storage_account_creation_validation

  cloudify.azure.nodes.NIC:
    derived_from: cloudify.nodes.Root
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create network interface card. 
        type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
        type: string
        default: 'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine required to create network interface card
        type: string
        default: 'my_vm'
      
    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.nic.create_nic
        delete: azure.nic.delete_nic
      cloudify.interfaces.validation:
        creation: azure.nic.nic_creation_validation

  cloudify.azure.nodes.VNET:
    derived_from: cloudify.nodes.Network
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create virtual network. 
        type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
        type: string
        default: 'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine required to create virtual network
        type: string
        default: 'my_vm'
      
    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.vnet.create_vnet
        delete: azure.vnet.delete_vnet
      cloudify.interfaces.validation:
        creation: azure.vnet.vnet_creation_validation

relationships:
  cloudify.azure.relationships.instance_connected_to_public_ip:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish: azure.server.create_public_ip
        unlink: azure.delete.delete_public_ip
