##################################################################################
# Cloudify Azure built in types and plugins definitions.
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-azure-plugin/archive/1.3m4.zip

node_types:
  cloudify.aws.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      location:
        description: >
          Indicates the location where VM will be provisioned
        type: string
        default:'West US'
      subscription_id:
        description: >
          Indicates the subscription id of user account
        type: string
        default:''
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default:'my_vm'
      vm_size:
        description: >
          Indicates the size of VM
        type: string
        default: 'Standard A0'
      vm_os_type:
        description: >
          Flavour of virtual machine
        type: string
        default:'UbuntuServer'
     vm_admin_username:
        description: >
           Indicates admin username for VM
        type: string
        default:'UbuntuServer'
     
     
      parameters:
        description: >
          The key value pair parameters allowed by Amazon API to the
          ec2.connection.EC2Connection.run_instances command. It should be mentioned that
          although this field is listed as optional. A non-trivial use case requires
          that both the key_name parameter and the security_groups parameter be specified.
        default: {}
      azure_config:
        description: >
          A dictionary of values to pass to authenticate with the AWS API.
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.server.create_vm
        start:
          implementation: azure.server.start_vm
        stop:
          implementation: azure.server.stop_vm
        delete:
          implementation: azure.delete.delete_virtual_machine
      cloudify.interfaces.validation:
        creation:
          implementation: azure.server.vm_creation_validation

  cloudify.azure.nodes.create_public_ip:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create public ip address. 
      type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
      type: string
         default:'West US'
      publicIPAllocationMethod:
        description: >
          Indicates how the IP address will be allocated. It can be either dynamically or statically
      type: string
         default: 'Dynamic'

    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.server.create_public_ip
        delete: azure.delete.delete_public_ip
      cloudify.interfaces.validation:
        creation: azure.server.public_ip_creation_validation

    

relationships:
  cloudify.azure.relationships.instance_connected_to_public_ip:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish: azure.server.craete_public_ip
        unlink: azure.delete.delete_public_ip
 
