##################################################################################
# Cloudify Azure built in types and plugins definitions.
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-azure-plugin/archive/master.zip

node_types:
  cloudify.azure.nodes.VirtualMachine:
    derived_from: cloudify.nodes.Compute
    properties:
      location:
        description: >
          Indicates the location where VM will be provisioned
        type: string
        default:'West US'
      subscription_id:
        description: >
          Indicates the subscription id of user account
        type: string
        default:''
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default:'my_vm'
      vm_size:
        description: >
          Indicates the size of VM
        type: string
        default: 'Standard A0'
      vm_os_type:
        description: >
          Flavour of virtual machine
        type: string
        default:'UbuntuServer'
      keyData:
        description: >
           Indicates the ssh key data of the user
        type: string
        default:''
      client_id:
        description: >
           Indicates the client id required to create VM
        type: string
        default:''
    
      tenant_id:
        description: >
           Indicates the tenant id required to create VM
        type: string
        default:''
      username:
        description: >
           Indicates the username 
        type: string
        default:''
        
      password:
        description: >
           Indicates the password of the user.  
        type: string
        default:''
    
    
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.server.create_vm
        start:
          implementation: azure.server.start_vm
        stop:
          implementation: azure.server.stop_vm
        delete:
          implementation: azure.delete.delete_virtual_machine
      cloudify.interfaces.validation:
        creation:
          implementation: azure.server.vm_creation_validation

  cloudify.azure.nodes.PublicIP:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create public ip address. 
      type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
      type: string
         default:'West US'
      publicIPAllocationMethod:
        description: >
          Indicates how the IP address will be allocated. It can be either dynamically or statically
      type: string
         default: 'Dynamic'

    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.server.create_public_ip
        delete: azure.delete.delete_public_ip
      cloudify.interfaces.validation:
        creation: azure.server.public_ip_creation_validation

    

  cloudify.azure.nodes.StorageAccount:
     derived_from: cloudify.nodes.Container
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create public ip address. 
      type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
      type: string
         default:'West US'
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default:'my_vm'
      

    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.server.create_storage_account
        delete: azure.delete.delete_storage_account
      cloudify.interfaces.validation:
        creation: azure.server.storage_account_creation_validation


  cloudify.azure.nodes.NIC:
     derived_from: cloudify.nodes.Root
    properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create network interface card. 
      type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
      type: string
         default:'West US'
       vm_name:
        description: >
          Indicates the name of the virtual machine required to create network interface card
        type: string
        default:'my_vm'
      
      

    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.server.create_nic
        delete: azure.delete.delete_nic
      cloudify.interfaces.validation:
        creation: azure.server.nic_creation_validation


  cloudify.azure.nodes.VirtualNetwork:
     derived_from: cloudify.nodes.Network
     properties:
      subscription_id:
        description: >
          Indicates the subscription id required to create virtual network. 
      type: string
        default: ''
      location:
        description: >
         location where VM will be provisioned
      type: string
         default:'West US'
       vm_name:
        description: >
          Indicates the name of the virtual machine required to create virtual network
        type: string
        default:'my_vm'
      
    interfaces:
      cloudify.interfaces.lifecycle:
        create: azure.server.create_vnet
        delete: azure.delete.delete_vnet
      cloudify.interfaces.validation:
        creation: azure.server.vnet_creation_validation




relationships:
  cloudify.azure.relationships.instance_connected_to_public_ip:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish: azure.server.create_public_ip
        unlink: azure.delete.delete_public_ip
 
