##################################################################################
# Cloudify Azure built in types and plugins definitions.
##################################################################################

plugins:
  azure:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-azure-plugin/archive/1.3m4.zip

node_types:
  cloudify.azure.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      location:
        description: >
          Indicates the location where VM will be provisioned
        type: string
        default:'West US'
      subscription_id:
        description: >
          Indicates the subscription id of user account
        type: string
        default:''
      vm_name:
        description: >
          Indicates the name of the virtual machine
        type: string
        default:'my_vm'
      vm_size:
        description: >
          Indicates the size of VM
        type: string
        default: 'Standard A0'
      vm_os_type:
        description: >
          Flavour of virtual machine
        type: string
        default:'UbuntuServer'
     vm_admin_username:
        description: >
           Indicates admin username for VM
        type: string
        default:'UbuntuServer'
    
    
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: azure.server.create_vm
        start:
          implementation: azure.server.start_vm
        stop:
          implementation: azure.server.stop_vm
        delete:
          implementation: azure.delete.delete_virtual_machine
      cloudify.interfaces.validation:
        creation:
          implementation: azure.server.vm_creation_validation

  cloudify.aws.nodes.VIP:
    derived_from: cloudify.nodes.VirtualIP
    

 
