version: 2.1

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  node: cloudify/public-unittest-orb@volatile
  wagonorb: cloudify/wagon-bulder-orb@volatile
  releaseorb: cloudify/release-orb@volatile
  managerorb: cloudify/manager-orb@volatile
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  cloudify-machine-py3:
    machine:
      image: ubuntu-2004:202201-02

commands:

  setup_manager:
    steps:
      - run: |
          if [[ -z "${CLOUDIFY_HOST}" ]]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TENANT}" ]]; then
              exit 1
          fi
      - run: |
          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
              exit 1
          fi
      - run: |
          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
          if [[ $response != 200 ]]; then
              echo "Failed to get manager status";
              exit 1
          fi
      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
      - run: git submodule update --init --recursive --remote

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-remote-test-manager -es azure_client_id=$azure_client_id -es azure_client_secret=$azure_client_secret -es azure_location=$azure_location -es azure_subscription_id=$azure_subscription_id -es azure_tenant_id=$azure_tenant_id -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn*)  ~/project/plugin.yaml
      - run: ecosystem-test upload-plugin -PN utilities
      - run: ecosystem-test upload-plugin -PN ansible
      - run: ecosystem-test upload-plugin -PN kubernetes

  run_hello_world_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/hello-world-example/azure.yaml --test-id=hello-world-example-$CIRCLE_BUILD_NUM -i env_name=azpl -i resource_suffix=test$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=1800 | tee -a run_hello_world_test.log
      - store_artifacts:
          path: run_hello_world_test.log
      - slack/notify_failed

  run_azure_arm_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/blueprint-examples/virtual-machine/azure-arm.yaml --test-id=virtual-machine-$CIRCLE_BUILD_NUM -i env_name=azpl -i resource_suffix=test$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=1800 | tee -a run_azure_arm_test.log
      - store_artifacts:
          path: run_azure_arm_test.log
      - slack/notify_failed

  run_aks_test:
    steps:
      - run: |
          export ENV_NAME=t${CIRCLE_BUILD_NUM: -2}
          ecosystem-test remote-blueprint-test -b examples/blueprint-examples/kubernetes/azure-aks/blueprint.yaml --test-id=azure-aks-$CIRCLE_BUILD_NUM -i env_name=$ENV_NAME --on-failure=uninstall-force --timeout=3000 | tee -a run_aks_test.log
      - store_artifacts:
          path: run_aks_test.log
      - slack/notify_failed

  run_lb_test:
    steps:
      - run: ecosystem-test remote-blueprint-test -b examples/load-balancer-blueprint.yaml --test-id=azure-lb-$CIRCLE_BUILD_NUM -i resource_prefix=lb-test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000 | tee -a run_lb_test.log
      - store_artifacts:
          path: run_lb_test.log
      - slack/notify_failed

jobs:

  hw_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_hello_world_test

  lb_integration_test:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_lb_test

  azure_arm_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_azure_arm_test

  aks_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - managerorb/create_manager_container_latest
      - prepare_test_manager
      - run_aks_test

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - node/validate_version_job
      - node/validate_documentation_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - hw_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - azure_arm_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - aks_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - lb_integration_test:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - releaseorb/release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
            - hw_integration_tests_py3
            - azure_arm_integration_tests_py3
            - aks_integration_tests_py3
      - releaseorb/merge_docs_job:
          filters:
            branches:
              only: /master/
          requires:
            - releaseorb/release
            - node/validate_documentation_job
  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - hw_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/arch64_wagon
            - wagonorb/wagon_311
            - wagonorb/wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - azure_arm_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/arch64_wagon
            - wagonorb/wagon_311
            - wagonorb/wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - aks_integration_tests_py3:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/arch64_wagon
            - wagonorb/wagon_311
            - wagonorb/wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/

  lb_weekly_test:
    triggers:
    - schedule:
        cron: "0 1 * * 2"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
      - node/validate_version_job
      - wagonorb/wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/wagon_311:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - wagonorb/rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - lb_integration_test:
          context: 
            - plugins-inputs
          <<: *unittest-post-steps
          requires:
            - wagonorb/wagon
            - wagonorb/wagon_311
            - wagonorb/arch64_wagon
            - wagonorb/rhel_wagon
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
